EventHubConfig:
  connection: Endpoint=sb://FctsNAMemNADevlEvtHub01.servicebus.windows.net/;SharedAccessKeyName=<KeyName>
  EventHubName: honeywell-uas-oem-alarms

RabbitConfig:
  ConnectionString:
  QueueName: "oem"

ControllerConfig:
  Frequency: 1000
  MaxDataPoint: 20
  DataDefinition: /Users/christophebuffard/Documents/Dev/github.com/oem-sim-g/assets.jsonl