EventHubConfig:
  connection: Endpoint=sb://FctsNAMemNADevlEvtHub01.servicebus.windows.net/;SharedAccessKeyName=<KeyName>
  EventHubName: honeywell-uas-oem-alarms

ControllerConfig:
  Frequency: 1
  MaxDataPoint: 20
  DataDefinition: /Users/christophebuffard/Documents/Dev/github.com/oem-sim-g/assets.jsonl